# Generated by Django 4.2.7 on 2025-08-26 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('operator_type', models.CharField(choices=[('AIRLINE', 'Airline'), ('RAILWAY', 'Railway'), ('BUS_COMPANY', 'Bus Company')], max_length=12)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='operator_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Operator',
                'verbose_name_plural': 'Travel Operators',
                'db_table': 'travel_operators',
            },
        ),
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('travel_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('TRAIN', 'Train'), ('BUS', 'Bus')], max_length=10)),
                ('operator_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('source_code', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_code', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats', models.PositiveIntegerField()),
                ('total_seats', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('baggage_allowance', models.CharField(blank=True, max_length=100, null=True)),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Option',
                'verbose_name_plural': 'Travel Options',
                'db_table': 'travel_options',
                'ordering': ['departure_datetime'],
                'indexes': [models.Index(fields=['travel_type', 'source', 'destination'], name='travel_opti_travel__5b8aa4_idx'), models.Index(fields=['departure_datetime'], name='travel_opti_departu_6ea43f_idx'), models.Index(fields=['status'], name='travel_opti_status_64caac_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Popular Route',
                'verbose_name_plural': 'Popular Routes',
                'db_table': 'popular_routes',
                'unique_together': {('source', 'destination')},
            },
        ),
    ]
