# Generated by Django 4.2.7 on 2025-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveloperator',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
